In [1]:
import numpy as np

### making two demensional array

In [2]:
arr1 = np.array([[2,3,4,5],[3,7,5,9]])

#### if i put axis = 1 it will sum all the 'X' axis value in a list (and it means row wise)

In [3]:
arr1.sum(axis = 1)

array([14, 24])

#### if i put axis = 0 it will sum all the 'Y' axis value in a list (in simple term colon wise)

In [4]:
arr1.sum(axis = 0)

array([ 5, 10,  9, 14])

In [5]:
b = np.array([[7,8,9,4],[2,8,0,1]])

In [6]:
b1 = np.array([[7,8,9],[2,8,1]])

In [7]:
arr1.dot(b.transpose())

array([[ 94,  33],
       [158,  71]])

In [8]:
# dir(arr1)

In [9]:
arr2 = np.array([[2,3,4],[3,7,5]])

In [10]:
np.cross(arr2,b1)

array([[ -5,  10,  -5],
       [-33,   7,  10]])

In [11]:
np.sort(arr2)

array([[2, 3, 4],
       [3, 5, 7]])