In [1]:
import numpy as np

In [2]:
a = np.arange(7)

In [3]:
a

array([0, 1, 2, 3, 4, 5, 6])

In [4]:
b = np.array([1,23,45,78,98,65,32,12,45,7,8,98,46,64,13])
b

array([ 1, 23, 45, 78, 98, 65, 32, 12, 45,  7,  8, 98, 46, 64, 13])

In [5]:
#it sort array and show output in index wise
np.argsort(b)

array([ 0,  9, 10,  7, 14,  1,  6,  2,  8, 12, 13,  5,  3,  4, 11],
      dtype=int64)

In [6]:
#it shows minimum value in array in index form
np.argmin(b)

0

In [7]:
#it shows max value in array in index form
np.argmax(b)

4

In [8]:
b2 = np.array([1,23,45,78,98,65,32,12,45,7,8,98,46,64,13])
# b2.shape
b2 = b2.reshape(5,3)

In [9]:
b2

array([[ 1, 23, 45],
       [78, 98, 65],
       [32, 12, 45],
       [ 7,  8, 98],
       [46, 64, 13]])

In [10]:
#now it sort elements in x as array
np.argsort(b2)

array([[0, 1, 2],
       [2, 0, 1],
       [1, 0, 2],
       [0, 1, 2],
       [2, 0, 1]], dtype=int64)

In [11]:
#in this sorting we give extra command which is axis = 0 so now it sorts array in y axis
np.argsort(b2 , axis =0)

array([[0, 3, 4],
       [3, 2, 0],
       [2, 0, 2],
       [4, 4, 1],
       [1, 1, 3]], dtype=int64)